# Generated by Django 5.2.6 on 2025-10-18 17:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('update', 'Update'), ('analysis', 'Analysis'), ('exclusive', 'Exclusive'), ('rumor', 'Rumor'), ('match', 'Match')], max_length=20)),
                ('sports', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('volleyball', 'Volleyball'), ('motogp', 'Motogp')], max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('news_views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
