# Generated by Django 5.2.8 on 2025-11-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('volleyball', 'Volleyball'), ('motogp', 'Motogp')], default='football', max_length=20),
        ),
    ]
