# Generated by Django 5.2.7 on 2025-10-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('registered', 'Registered'), ('content_staff', 'Content Staff')], default='registered', max_length=20),
        ),
    ]
