# Generated by Django 5.2.6 on 2025-10-23 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
        ('news', '0002_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionthread',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_threads', to='news.news'),
        ),
        migrations.AlterField(
            model_name='discussionthread',
            name='body',
            field=models.TextField(),
        ),
    ]
